[build]
command = "npm run build"
publish = "build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
REACT_APP_API_URL = "/.netlify/functions/api" # Replace this with your serverless function endpoint
